apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Mongodb
  annotations:
     argocd/app-name: mongo
  namespace: default
spec:
  type: database
  owner: group:default/guests
  system: examples
